name: Context Testing

on: push

jobs:
  github-context: 
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Look for actor
        run: |
          echo "Actor here is ${{ github.actor }} "
