name: Inline workflow scripts

on: push

jobs:
  script_writing:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          
      - name: Executing the inline script
        shell: python
        run: |
          import os
          import platform

          print("Hello from native inline Python!")
          print(f"OS Platform: {platform.system()}")
          
