#name: Sample Workflow
name: Conditional Workflow

on: 
   push:
   #repository_dispatch:
   #   types:
   #      - my-custom-event
         
   #schedule:
    #  - cron: "*/5 * * * *"
   #workflow_dispatch:
   #   inputs:
   #      Name: 
   #         description: Name of user to greet
   #         required: true
   #         type: string
   #         default: "Madhura"
   #      Gender:
   #         description: gender of the baby
   #         required: true
   #         type: string
   
   #push:
    #  branches:
    #     - main

jobs:
   Conditional_testing:
      if: github.event_name == 'push'
   #sample:
      runs-on: ubuntu-latest
      steps:
         - name: Webhook event #Gender Reveal
           run: 
             echo "Hello, this is a webhook-triggered event"
              #echo "Hello ${{inputs.Name}}, it's a ${{inputs.Gender}}"
         
         #- name: Greetings 
        #   uses: actions/hello-world-javascript-action@v1
        #   with: 
        #     who-to-greet: "World" 

        
