name: Sample Workflow

on: 
   schedule:
      - cron: "*/1 * * * *"
   workflow_dispatch:

jobs:
   sample:
      runs-on: ubuntu-latest
      steps:
         - name: Greetings 
           uses: actions/hello-world-javascript-action@v1
           with: 
             who-to-greet: "World" 
