name: Test the custom action

on: push

jobs:
  test_the_custome_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Test the custom action
        uses: ./custom_hello/greet/action.yaml
        id: hello-step
        with: 
          greeting_name: "Madhura"
      - name: Get the Action Output
        run: echo "The action finished at ${{ steps.hello-step.outputs.greeting }}"

        
