name: Workflow Commands

on: push

env:
  global_var: "I am a duck"

jobs:
  commands:
     runs-on: ubuntu-latest
     steps:
       - name: Test the GitHub env command
         run: |
           echo "animal=duck" >> $GITHUB_ENV
       - name: Test the GitHub env command for printing
         run: |
           echo $animal
       - name: Test built-in GitHub commands
         run: |
           echo $GITHUB_ACTOR
       - name: Test built-in GitHub commands
         run: |
           echo $global_var
           
                
